export const FETCH_ITEMS_START = 'FETCH_ITEMS_START'
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL'

export const SORTING_PRODUCTS = 'SORTING_PRODUCTS'

export const ADD_TO_CART = 'ADD_TO_CART';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const CLEAR_CART = 'CLEAR_CART';

export const INCREASED_QUANTITY = 'INCREASED_QUANTITY';

export const DECREASED_QUANTITY = 'DECREASED_QUANTITY';

export const UPDATE_CART_INFO_SUCCESS = 'UPDATE_CART_INFO_SUCCESS'